#!/bin/bash

#check for required commands, exit if failed
required_commands=('xmllint' 'exiv2' 'curl')
for cmd in "${required_commands[@]}"; do
	if ! command -v ${cmd} >/dev/null 2>&1; then
		missing_commands+=(${cmd})
	fi
done

if (( ${#missing_commands[@]} > 0)); then
	echo "Error: missing commands 
	${missing_commands[@]}" >&2
	exit 2
fi

#help command output
usage () {
	echo "Usage:  boorutag [FLAGS] file(s)
boorutag [FLAGS] -d [DIRECTORY]

Example: boorutag -oU -S d -d ~/Pictures/homework
  ((o)verwrites tags, (U)pscales samples, only (S)ite danbooru, on each file in ~/Pictures/homework
	
  Flags: (indev ver. ! marked tags not implemented)
  !-d [dir]   run on all files of given directory
  -t [0-2]   tag format [0(default): both | 1: IPTC | 2: XMP]
  !-S [site]  search only in given site [(g)elbooru, (d)anbooru, (r)ule34]
  !-r 	     disable reverse image search fallback
  !-u 	     always download full-res image for samples if available
  !-U 	     same as -u but OVERWRITES the image (its gone for good!)
  -o	     overwrite existing tag/exif data
  !-s	     silent mode (no output)
  !-v	     verbose mode (more output)
  -h	     display this help message" >&2;
	exit 1
}

while getopts ":d:t:S:ruUosvh" opt; do
	case $opt in
		d) if [[ -d ${OPTARG} ]]; then directory=${OPTARG}; else
			echo "Error: flag -d | directory '${OPTARG}' not found or invalid" >&2; exit 2; fi ;;
		t) if ! [[ ${OPTARG} =~ ^[0-2]$ ]]; then
			echo "Error: flag -t | invalid option '${OPTARG}' - valid options are [0, 1, 2]" >&2; exit 2; else
			tagFormat=${OPTARG}; fi ;;
		S) shopt -s nocasematch
			case ${OPTARG} in 
				g|gelbooru) ;;
				d|danbooru) ;;
				r|rule34) ;;
				*) echo "Error: flag -S | invalid option '${OPTARG}' | boorutag -h for usage" >&2; exit 2 ;;
			esac; shopt -u nocasematch;;
		r) reverseFallback="0" ;;
		u) alwaysUpscale="1" ;;
		U) alwaysUpscale="2" ;;
		o) clearData="1" ;;
		s) silent="1" ;;
		v) verbose="1" ;;
		h) usage ;;
		?) echo "Error: Invalid flag -$OPTARG" >&2; exit 2 ;;
		:) echo "Error: -$OPTARG requires an argument" >&2; exit 2 ;;
	esac
done
shift "$(($OPTIND -1))"


CONFIG_DIR="${HOME}/.config/boorutag"
KEYS="${CONFIG_DIR}/api_keys"
mkdir -p ${CONFIG_DIR}
source "$KEYS"

#look for keys, prompt if they dont exist
if [[ -z ${gelApi} ]]; then
	echo "Gelbooru API key not found, enter it to proceed"
	read -r gelApi
	: > "$KEYS"
	printf 'gelApi="%s"\n' "$gelApi" >> "$KEYS"
fi

#base link for searches using md5
gelLink="https://gelbooru.com/index.php?page=dapi&s=post&q=index${gelApi}&tags=md5:"

#extract MD5 hash from filename if it exists, return 3 on fail
#expects filename (basename)
getMD5 () {
	local outMD5=$(grep -oP "[a-f\d]{32}" <<< $1)
	if [[ -z ${outMD5} ]]; then 
		echo "failed to find MD5 data of file $1" >&2
		exit 3
	else
		echo ${outMD5}
	fi
}

#get xml from booru api and return tags
fetchBooruData () {
	local xmlResult=$(curl --silent --request GET "${gelLink}$1")
	echo $(xmllint --xpath '//tags/text()' - <<<${xmlResult})
}

# sample (low-res) detection
sampleCheck () {
	if [[ $1 =~ "sample" ]]; then
		echo "Current file detected as sample, download high-res? [Y/n]" >&2
		read -r -s -n 1 ans
		case $ans in
			[Nn]) break ;;
			[Yy]|"") sampleDownload INEEDTOPUTTHEDATAHEREPLEASEDONTFORGETJINGLEJINGLE ;;
			*) echo 'Invalid option, answer Y or N.'; sampleCheck $1 ;;
		esac
	fi

}

#set tags according to tag format (0 - both | 1 - IPTC | 2 - XMP), optionally clear existing tags before
#expects string of space-seperated tags
setTags () {
	local file=$1
	shift
	local tags="$@"
	#remove all exif, iptc, and xmp data
	if [[ ${clearData} -eq "1" ]]; then exiv2 rm ${file}; fi

	#iterate through tags and apply to IPTC 
	if [[ ${tagFormat} -eq "0" || ${tagFormat} -eq "1" ]]; then
		for t in ${tags}; do
			exiv2 -M "add Iptc.Application2.Keywords '${t}'" ${file}
		done
	fi

	#add commas and apply to XMP
	if [[ ${tagFormat} -eq "0" || ${tagFormat} -eq "2" ]]; then
		exiv2 -M "add Xmp.iptc.Keywords XmpBag ${tags// /, }" ${file}
	fi

}

declare -i progress
for f in "$@"; do
	progress+=1
	if ! [[ -r $f && -w $f ]]; then
		echo "Error: read/write error on file '$f', skipping." >&2;
		continue;
	fi
	echo "[${progress}/$#] - $f"
	Filename=$(basename $f)
	MD5=$(getMD5 ${Filename})
	Tags=$(fetchBooruData ${MD5})
	# sampleCheck $f
	setTags $f ${Tags}
	sleep 0.1 #good enough for rate limiting :3
done
