#!/bin/bash

#check for required commands, exit if failed
required_commands=('xmllint' 'exiv2' 'curl' 'md5sum')
for cmd in "${required_commands[@]}"; do
	if ! command -v ${cmd} >/dev/null 2>&1; then
		missing_commands+=(${cmd})
	fi
done

if (( ${#missing_commands[@]} > 0)); then
	echo "${ERRORMSG} missing commands 
	${missing_commands[@]}" >&2
	exit 2
fi

CONFIG_DIR="${HOME}/.config/boorutag"
KEYS="${CONFIG_DIR}/api_keys"
mkdir -p ${CONFIG_DIR}
source "$KEYS"

RED='\033[1;31m'; GREEN='\033[1;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
if [ ! -t 1 ]; then
  RED=''; GREEN=''; YELLOW=''; NC=''
fi
ERRORMSG="${RED}[ERROR]${NC} - "; STATUSMSG="${YELLOW}[STATUS]${NC} - "
logMsg () {
	[[ ${silent} -gt 0 ]] && return 0
	case $1 in
		0) local msg_type='' ;;
		1) local msg_type=${STATUSMSG} local void_logs=''; ;; 
		2) local msg_type=${ERRORMSG} local void_logs=''; ;; 
		3) local msg_type=${STATUSMSG}; local void_logs="/dev/null"; ;; 
		4) local msg_type=${ERRORMSG}; local void_logs="/dev/null"; ;;
	esac

	#skip logging if opt 3/4, but still write to stderr
	echo -e "${msg_type}$2\033[K" | tee -a "${LOG_DIR:-${CONFIG_DIR}}/latest.log" >&2

}

#help command output
usage () {
	echo "Usage:  boorutag [FLAGS] file(s)
boorutag [FLAGS] -d [DIRECTORY]

Example: boorutag -oU -S d -d ~/Pictures/homework
  ((o)verwrites tags, (U)pscales samples, only (S)ite danbooru, on each file in ~/Pictures/homework
	
  Flags: (indev ver. ! marked tags not implemented)
  !-d [dir]   run on all files of given directory
  -t [IX]     tag format to write [(I)PTC and/or (X)MP] (default: IX) 
  -l [dir]    where to save log file to (defaults to '${CONFIG_DIR}/boorutag/latest.log')	
  -u [0-3]	  upscaling mode, check site result for higher-res image, [0 - never, 1 - prompt for each, 2 - always, 3 - always & overwrite file]
  !-S [site]  search only in given site [(g)elbooru, (d)anbooru, (r)ule34]
  -m	      generate and try matching against output of md5sum (THIS WILL WIPE EXIF DATA)
  -M	      same as -m, but also renames the file to correct MD5 if match is found
  !-r 	      disable reverse image search fallback
  -o	      overwrite existing tag/exif data
  -s	      silent mode (no output)
  !-v	      verbose mode (more output)
  -h	      display this help message" >&2;
	exit 1
}

while getopts ":d:t:l:u:S:mMrosvhw" opt; do
	case $opt in
		d) if [[ -d ${OPTARG} ]]; then directory=${OPTARG}; else
			logMsg 4 "flag -d | directory '${OPTARG}' not found or invalid"; exit 2; fi ;;
		t) if ! [[ ${OPTARG} =~ ^([Ii]?[Xx]?$|^[Xx]?[Ii]?)$ ]]; then
			logMsg 4 "flag -t | invalid option '${OPTARG}' - valid options are [I,X,IX]"; exit 2; else
			tag_format="${OPTARG^^}"; fi ;;
		l) if [[ -d ${OPTARG} ]]; then LOG_DIR=${OPTARG}; else logMsg 4 "flag -l | expected directory but got '${OPTARG}'"; exit 2; fi ;;
		u) case ${OPTARG} in
			[0-3]) always_upscale=${OPTARG} ;;
			*) logMsg 4 "flag -S | invalid option '${OPTARG}' | boorutag -h for usage"; exit 2 ;;
		esac ;;
		S) shopt -s nocasematch
			case ${OPTARG} in 
				g|gelbooru) ;;
				d|danbooru) ;;
				r|rule34) ;;
				*) logMsg 4 "flag -S | invalid option '${OPTARG}' | boorutag -h for usage"; exit 2 ;;
			esac; shopt -u nocasematch;;
		m) gen_md5="1" ;;
		M) gen_md5="2" ;;
		r) reverse_fallback="0" ;;
		o) overwrite_tags="1" ;;
		s) silent="1" ;;
		v) verbose="1" ;;
		h) usage ;;
		w) weebtrash="$(base64 -d <<< "bnlhISBhbGwgZmlsZXMgcHdvY2Vzc2VkIHNlbnBhaX4K")" ;;
		?) logMsg 4 "Invalid flag -$OPTARG"; exit 2 ;;
		:) logMsg 4 "OPTARG' requires an argument"; exit 2 ;;
	esac
done
if [[ $# -eq 0 ]]; then usage; fi
shift "$(($OPTIND -1))"
tag_format=${tag_format:-XI}
LOG_DIR="${LOG_DIR:-${CONFIG_DIR}}"
echo -e "〜ボールタグ(v0.5)\n" > "${LOG_DIR}/latest.log"



#look for keys, prompt if they dont exist
if [[ -z ${gelApi} ]]; then
	echo "Gelbooru API key not found, enter it to proceed"
	read -r gelApi
	: > "$KEYS"
	printf 'gelApi="%s"\n' "$gelApi" >> "$KEYS"
fi

#base link for searches using md5
gel_link="https://gelbooru.com/index.php?page=dapi&s=post&q=index${gelApi}&tags=md5:"

#extract MD5 hash from filename if it exists, return 1 on fail
#expects file in
getMD5 () {
	local filename=$(basename $1)
	local outMD5=$(grep -oP "[a-f\d]{32}" <<< $filename)
	if [[ -n ${outMD5} ]]; then echo ${outMD5}; else
		logMsg 1 "Failed to find MD5 data of file '$filename' in filename${gen_md5:+", trying from md5sum"}"

		if [[ ${gen_md5} -gt 0 ]]; then
			exiv2 rm $1
			outMD5=$(md5sum $1)
			echo "${outMD5%% *}"
			return 0
		else return 1; 
		fi

	fi
}

#get xml from booru api and return tags
# expects $1, data to extract, $2 MD5 string (or leave empty for last result)
fetchBooruData () {
	if [[ $1 != "xml" && -z ${XML} ]]; then logMsg 2 "fetchBooruData() was called but XML is empty?"; return 2; fi;
	case $1 in 
		"xml")
			local data_out=$(curl --silent --request GET "${gel_link}$2") ;;
		"tags") 
			local data_out=$(xmllint --xpath '//tags/text()' - <<<${XML} 2>/dev/null ) ;;
		"file") 
			local data_out=$(xmllint --xpath '//file_url/text()' - <<<${XML} 2>/dev/null ) ;;
		"size")
			local data_out=$(xmllint --xpath '//width/text()' - <<<${XML} 2>/dev/null ) ;;
	esac
	if [[ $? -gt 0 || -z ${data_out} ]]; then 
		logMsg 2 "{fetchBooruData() failed, case '$1', MD5: ${2:-'not set'}, data_out ${data_out:-'not set'}"
		return 1
	else
		echo ${data_out}
	fi
}

# sample (low-res) detection, expects file in
sampleCheck () {
	local regex="([0-9]*) x [0-9]*"
	if [[ $1 =~ "sample" ]] || ! [[ $(exiv2 $1 2>&1) =~ ${regex} && ${BASH_REMATCH[1]} =~ $(fetchBooruData "size") ]]; then
		case ${always_upscale} in 
			1) 
				logMsg 1 "File '$1' detected as sample, download high-res? [Y/r/n] (r to replace)" 
				read -r -s -n 1 ans
				case $ans in
					[Nn]) return 2 ;;
					[Yy]|"") sampleDownload 1 $1 ;;
					[Rr]) sampleDownload 3 $1 ;;
					*) echo 'Invalid option, answer Y or N.'; sampleCheck $1 ;;
					#omg look at this beautiful triangle.. waow.
				esac
				;;
			2|3) 
				logMsg 1 "File '$1' detected as sample, downloading high-res..."
				sampleDownload ${always_upscale} $1
				;;
			*) logMsg 2 "Tried checking for sample with invalid -u opt, how did we get here??"
		esac
	else return 1;
	fi
}

# get full sized image from booru
# expects $1 [0-3] (3 replaces original file), $2 file
sampleDownload () {
	#shouldnt need to check that it exists in database, getMD5 should have caught that
	#slicing code below may also be sufficient, but extenstion sometimes differ so lets play it safe
	# local file_link="${MD5:0:2}/${MD5:2:2}/${MD5}"
	if local file_link=$(fetchBooruData "file" 1 ${MD5}); then
		local dir="${2%/*}"
		[[ $2 != */* ]] && dir=

		if curl -H "Referer: https://gelbooru.com/" -o "${dir:+$dir/}${file_link##*/}" ${file_link}; then 
			cur_file="${dir:+$dir/}${file_link##*/}"
			logMsg 1 "Sucessfully downloaded high-res file ${cur_file}"
		fi

	else
		logMsg 2 "Something went wrong downloading sample"
		return 1
	fi


}

#check for existing iptc or xmp data, return 0 if empty, 1 if not
checkTags () {
	[[ -n $(exiv2 -P ${tag_format}kyct $1) ]]; return $?
}

#set tags according to tag format (0 - both | 1 - IPTC | 2 - XMP), optionally clear existing tags before
#expects string of space-seperated tags
setTags () {
	local file=$1
	shift
	local tags="$@"
	#remove all exif, iptc, and xmp data
	if [[ ${overwrite_tags} -eq 1 ]]; then exiv2 -d eIx ${file}; fi

	#iterate through tags and apply to IPTC 
	if [[ $tag_format =~ I ]]; then
		for t in ${tags}; do
			exiv2 -M "add Iptc.Application2.Keywords '${t}'" ${file}
		done
	fi

	#add commas and apply to XMP
	if [[ ${tag_format} =~ X ]]; then
		exiv2 -M "add Xmp.iptc.Keywords XmpBag ${tags// /, }" ${file}
	fi

	#rename file since proper md5 was generated if we made it this far
	if [[ ${gen_md5} -eq 2 ]]; then 
		local dir="${file%/*}"
		[[ ${file} != */* ]] && dir=
		local new="${dir:+$dir/}${MD5}.${file##*.}"
		if [[ ${file} != ${new} ]]; then
		  	mv ${file} ${new}
			logMsg 1 "renamed '${file}' > '${new}'"
			cur_file=${new}
		fi
	fi
}

total_args=$#
progress () { 
	[[ ! ${silent} -gt 0 ]] && echo -e "[${GREEN}${#suc[@]}${NC}|${RED}${#fail[@]}${NC}|${total_args}] - $1" 
}

for f in "$@"; do
	cur_file=$f
	progress "${cur_file}"

	#check that file exists and is r/w capable
	if ! [[ -r $cur_file && -w $cur_file ]]; then
		logMsg 2 "Read/write error on file '$cur_file', skipping."
		fail+=("$cur_file [r/w error]")
		continue
	fi
	
	#check that file is a valid image
	if ! [[ "${f##*.}" =~ jpg|jpeg|png ]]; then
		logMsg 2 "File type error on file '$cur_file', skipping."
		fail+=("$cur_file [filetype error]")
		continue
	fi

	#skip file if tags exist and overwrite is disabled
	if [[ $overwrite_tags -ne 1 && ! $(checkTags $cur_file) ]]; then
		logMsg 1 "Tags exist for file '$cur_file', skipping."
		fail+=("$cur_file [tags exist]")
		continue
	fi

	MD5=$(getMD5 $cur_file)
	XML=$(fetchBooruData "xml" ${MD5})
	if Tags=$(fetchBooruData "tags"); then 
		[[ ${always_upscale} -ne 0 ]] && sampleCheck $cur_file
		setTags $cur_file ${Tags}
	else
		logMsg 2 "failed to retrieve tags for '$cur_file', skipping"
		fail+=("$cur_file [tag fail]")
		continue
	fi
	suc+=($cur_file)
	sleep 0.1 #good enough for rate limiting :3
done
progress "${weebtrash:-All done!} Log written at '${LOG_DIR}'"

#write overview of processed files to log
echo -e "\n[OVERVIEW]\n" >> "${LOG_DIR}/latest.log"
for i in "${suc[@]}"; do
	echo -e "${GREEN}+${NC} $i" >> "${LOG_DIR}/latest.log"
done
for i in "${fail[@]}"; do
	echo -e "${RED}-${NC} $i" >> "${LOG_DIR}/latest.log"
done
#create a time-stamped log file
cp "${LOG_DIR}/latest.log" "${LOG_DIR}/$(date +%y-%m-%d-%H%M).log"

